### ISSUE TITLE
Cannot launch pypr

### ISSUE THREAD

**Issue by zielOS** [hyprland-community/pyprland#12]
Hi I am getting this error when I try to launch pypr from terminal. I installed it manually following aur steps. Also tried using pip to install it. Both show the following error

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 165, in run_daemon
    await manager.load_config()  # ensure sockets are connected first
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 39, in load_config
    self.config = json.loads(f.read())
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 14 (char 13)
Exception ignored in: <function StreamWriter.__del__ at 0x7f317ec3d940>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 396, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/streams.py", line 344, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by kronikpillow** [comment]
I have the same issue it seems :-/

**Comment by fraschm1998** [comment]
Getting a similar issue, here's the output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 237, in main
    asyncio.run(run_daemon() if len(sys.argv) <= 1 else run_client())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 215, in run_client
    _, writer = await asyncio.open_unix_connection(CONTROL)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 98, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 259, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 642, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by fdev31** [comment]
I guess `pypr` daemon isn't running.
Did you add it to autostart or hyprland config ? Do you see any process running ?
`ps axuw |grep pypr`

Try running with `--debug /tmp/pypr.log` see if there is any error output in that file.

**Comment by lunigella** [comment]
I had the same issue after following the steps on the wiki. It seems that the default config provided lacks a comma after one bracket, just before the "unknown" part at the end of the file. Now it works for me.

**Comment by fdev31** [comment]
Hi! Two things:

@zielOS your JSON config file is invalid indeed. Check the first line, character 13:
```
json.decoder.JSONDecodeError: Extra data: line 1 column 14 (char 13)
```

@lunigella I can't find the typo, can you point it to help me?

All: would switching to TOML format a good idea ?

Pros: simpler & more flexible syntax, harder to break
Cons: would add two small dependencies to the python project

**Comment by lunigella** [comment]
I was referring to line 26 of the config provided in the Getting started session of the wiki.
...
    }, <-
    "unknown": "wlrlui"
  }
}
I have little to no experience with json, so I'm glad this solution worked for me but I'm not sure this will work with zielOS problem.

**Comment by fdev31** [comment]
> I was referring to line 26 of the config provided in the Getting started session of the wiki.

Thank you, just fixed it!

**Comment by zielOS** [comment]
yup that fixed it for me too.
