### ISSUE TITLE
[BUG] Pyprland shows "Client window not found" error when disabling eDP-1 monitor

### ISSUE THREAD

**Issue by nijek** [hyprland-community/pyprland#142]
**Pyprland version**
Which version did you use? 2.4.0

**Describe the bug**
I have a two monitor setup on Hyprland 0.43, my laptop monitor (eDP-1) and the HDMI monitor. If I login in my laptop, plug it to the hdmi and disable eDP-1 (so I can use only the HDMI monitor) pyprland shows error "Client window not found" and after a little while, if I try to acess the scratchpad again it crashed hyprland (only happens sometimes) 

**To Reproduce**
1. Start Hyprland on laptop
2. Plug laptop to the hdmi monitor
3. disable laptop eDP-1 (hyprctl keyword monitor "eDP-1, disable"
) monitor so I can use only the HDMI monitor
4. pypr shows error "Client window (window number) not found)
5. If I try to use the scratchpads again it crashes Hyprland sometimes

**Expected behavior**
Pypr should move the other monitor 

**Configuration (provide following files/samples when relevant):**
- pyprland.toml
- hyprland.conf
- debug log

[debug-log.txt](https://github.com/user-attachments/files/17228746/debug-log.txt)
[hyprland-config.txt](https://github.com/user-attachments/files/17228748/hyprland-config.txt)
[pyprland-config.txt](https://github.com/user-attachments/files/17228749/pyprland-config.txt)

**Comment by fdev31** [comment]
From the log it looks like the client window has crashed/ been closed:
```
Traceback (most recent call last):
  File "/var/cache/pypr/package.whl/pyprland/command.py", line 183, in _run_plugin_handler
    await getattr(plugin, full_name)(*params)
  File "/var/cache/pypr/package.whl/pyprland/plugins/scratchpads/__init__.py", line 307, in event_monitorremoved
    await self.run_hide(scratch.uid, autohide=True)
  File "/var/cache/pypr/package.whl/pyprland/plugins/scratchpads/__init__.py", line 726, in run_hide
    await scratch.update_client_info(clients=clients)
  File "/var/cache/pypr/package.whl/pyprland/plugins/scratchpads/objects.py", line 159, in update_client_info
    raise KeyError(msg)
KeyError: 'Client window 0x5f5c7cece830 not found'
```

Can you see the window in `hyprctl clients` ?

**Comment by fdev31** [comment]
I made it a bit more robust on git version, it should keep processing other scratchpads.

**Comment by fdev31** [comment]
Do you still experience the problem?

**Comment by fdev31** [comment]
Re-open if it hasn't been fixed.
