### ISSUE TITLE
Pyprland can't start because scratch.uid has no uid attribute

### ISSUE THREAD

**Issue by eggy111** [hyprland-community/pyprland#152]
**Pyprland version**
2.4.1 (nixos unstable)

**Describe the bug**
Attempting to start pyprland results in the error:
`Error initializing plugin scratchpads:
Traceback (most recent call last):
  File "/nix/store/d40c9sakv61gckr4135x2dk0pkx18cs8-pyprland-2.4.1/lib/python3.12/site-packages/pyprland/command.py", line 171, in __load_plugins_config
    await asyncio.wait_for(self.plugins[name].on_reload(), timeout=5.0)
  File "/nix/store/901c80rlps5q05bnjk1sj4zaz5k736nc-python3-3.12.7/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/nix/store/d40c9sakv61gckr4135x2dk0pkx18cs8-pyprland-2.4.1/lib/python3.12/site-packages/pyprland/plugins/scratchpads/__init__.py", line 103, in on_reload
    scratch.uid,
    ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'uid'
Command failed.
`

**Comment by fdev31** [comment]
It has been fixed in latest versions. Can you try 2.4.3 ?

**Comment by fdev31** [comment]
It's more than a month old, closing for inactivity. Re-open if it is still occurring.
