### ISSUE TITLE
Unable to hide scratchpad

### ISSUE THREAD

**Issue by fraschm1998** [hyprland-community/pyprland#17]
pyprland config:

```
{
  "pyprland": {
    "plugins": [
      "scratchpads"
    ]
  },
  "scratchpads": {
    "term": {
      "command": "foot",
      "animation": "fromTop",
      "unfocus": "hide"
    },
    "irc": {
      "command": "freetube-bin",
      "animation": "fromTop",
      "unfocus": "hide",
      "lazy": "true"
    },
    "qutebrowser": {
      "command": "qutebrowser",
      "animation": "fromTop",
      "lazy": "true"
    },
    "volume": {
      "command": "pavucontrol",
      "unfocus": "hide",
      "animation": "fromRight"
    }
  },
  "monitors": {
    "placement": {
      "LG 40WP95C-W": {
        "topOf": "DP-1"
      }
    }
  }
}
```

hyprland config:

```
bind = SUPER,Y,exec,pypr toggle irc
$irc  = ^(freetube-bin)$
windowrule = float,$irc
windowrule = workspace special silent,$irc
windowrule = size 50% 60%,$irc
windowrule = center,$irc
```

error:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 75, in _callHandler
    await getattr(plugin, full_name)(*params)
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 275, in run_toggle
    await self.run_show(uid)
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 385, in run_show
    await self.updateScratchInfo(item)
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 317, in updateScratchInfo
    await scratch.updateClientInfo()
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 129, in updateClientInfo
    raise AssertionError(e) from e
AssertionError
ERROR:scratch:client_info of  must be a dict: None
scratchpads::run_toggle(('irc',)) failed:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 124, in updateClientInfo
    assert isinstance(client_info, dict)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 75, in _callHandler
    await getattr(plugin, full_name)(*params)
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 273, in run_toggle
    await self.run_hide(uid)
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 336, in run_hide
    await self._anim_hide(animation_type, scratch)
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 283, in _anim_hide
    await self.updateScratchInfo(scratch)
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 317, in updateScratchInfo
    await scratch.updateClientInfo()
  File "/usr/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 129, in updateClientInfo
    raise AssertionError(e) from e
AssertionError
ERROR:scratch:client_info of  must be a dict: None
scratchpads::run_toggle(('irc',)) failed:
```

**Comment by fraschm1998** [comment]
Seems to only work if I start it while I'm looking at the specialworkspace. The window doesn't show up in a special workspace but on the current workspace instead.

**Comment by fdev31** [comment]
I can confirm the bug here, I'll check that when I'll have some time.

**Comment by fdev31** [comment]
The float problem can't be related to pyprland... check again your config regarding the class/title match eventually.
I think the next update (if you can't try git) will fix the pypr toggle issue.
