### ISSUE TITLE
Cannot Toggle scratchpads due to errors

### ISSUE THREAD

**Issue by redsteadz** [hyprland-community/pyprland#19]
Hi, I've been trying to use this for my setup but it keeps giving out the following error
```
ERROR:scratch:client_info of  must be a dict: None
scratchpads::run_toggle(('term',)) failed:

Traceback (most recent call last):
  File "/home/red/.local/pipx/venvs/pyprland/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 124, in updateClientInfo
    assert isinstance(client_info, dict)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red/.local/pipx/venvs/pyprland/lib/python3.11/site-packages/pyprland/command.py", line 75, in _callHandler
    await getattr(plugin, full_name)(*params)
  File "/home/red/.local/pipx/venvs/pyprland/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 275, in run_toggle
    await self.run_show(uid)
  File "/home/red/.local/pipx/venvs/pyprland/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 385, in run_show
    await self.updateScratchInfo(item)
  File "/home/red/.local/pipx/venvs/pyprland/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 317, in updateScratchInfo
    await scratch.updateClientInfo()
  File "/home/red/.local/pipx/venvs/pyprland/lib/python3.11/site-packages/pyprland/plugins/scratchpads.py", line 129, in updateClientInfo
    raise AssertionError(e) from e
AssertionError
```
Steps to recreate this
`
pypr
`
`
pypr toggle term
`
Gives out this exception 
Is it due to python version ? If so what version should I set it up using, thank you!

**Comment by fdev31** [comment]
Hi! I don't think it's Python related.
Which pyprland version are you using ?

**Comment by fdev31** [comment]
In every case, you may want to download & install https://github.com/hyprland-community/pyprland/tree/onlylazy to see if this problem still happens. I plan to merge this branch into the main one.

**Comment by redsteadz** [comment]
First of all thank you so much for the reply
And second, I'd like to apologize but... How would I go about installing this? I tried pyprland from paru and pipx and it worked flawlessly, But as this is a different branch it only contains python files
Please let me know at your convenience

**Comment by fdev31** [comment]
No worries.

I don't know pipx but it looks like you can use this syntax:

```
pipx install https://github.com/hyprland-community/pyprland@onlylazy
```

**Comment by redsteadz** [comment]
Thank you very much !
For anyone else wondering I used
```
pipx install git+https://github.com/hyprland-community/pyprland.git@onlylazy
```
To install it

**Comment by fdev31** [comment]
> Thank you very much !

So just to be 100% clear: using this version solved your issue ? :)

If you confirm, I'll make it the official branch, it works well for me for a couple of days.

**Comment by redsteadz** [comment]
> > Thank you very much !
> 
> So just to be 100% clear: using this version solved your issue ? :)
> 
> If you confirm, I'll make it the official branch, it works well for me for a couple of days.

Yes, functions perfectly !
