### ISSUE TITLE
pypr crashes on start due to missing tomllib

### ISSUE THREAD

**Issue by dantefromhell** [hyprland-community/pyprland#26]
Using commit 8a32727, I get the following stack trace:

```
Traceback (most recent call last):
  File "/nix/store/02p8hqpn1my8j1cb79z8r1c9pndjzx8w-python3.10-pyprland-1.5.1/bin/.pypr-wrapped", line 6, in <module>
    from pyprland.command import main
  File "/nix/store/02p8hqpn1my8j1cb79z8r1c9pndjzx8w-python3.10-pyprland-1.5.1/lib/python3.10/site-packages/pyprland/command.py", line 7, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'
```

According to [1] `tomllib` was added in Python 3.11, while `poetry` and the nix flake still point to Python 3.10.

[1] https://docs.python.org/3/library/tomllib.html

**Comment by A7R7** [comment]
I changed python310 to python311 in flake.nix. So far everything *seems* to work correctly.

**Comment by fdev31** [comment]
Oh my bad !! I thought this was an older addition and didn't check... I'm indeed using python3.11... I'll update the package dependency ! Thank you for reporting!
