### ISSUE TITLE
aur package is broken

### ISSUE THREAD

**Issue by Ultrahalf** [hyprland-community/pyprland#3]
```
==> Making package: pyprland 1.3.1-1 (Sun 14 May 2023 12:49:34 PM IST)
==> Retrieving sources...
  -> Cloning pyprland git repo...
Cloning into bare repository '/home/ultrahalf/.cache/paru/clone/pyprland/pyprland'...
remote: Enumerating objects: 268, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 268 (delta 14), reused 23 (delta 10), pack-reused 238
Receiving objects: 100% (268/268), 40.99 KiB | 545.00 KiB/s, done.
Resolving deltas: 100% (178/178), done.
==> Validating source files with md5sums...
    pyprland ... Skipped
==> Making package: pyprland 1.3.1-1 (Sun 14 May 2023 12:49:36 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating pyprland git repo...
==> Validating source files with md5sums...
    pyprland ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of pyprland git repo...
Cloning into 'pyprland'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
Note: switching to '1.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b117037 monitors: trigger the rules on init & reload
==> Sources are ready.
pyprland-1.3.1-1: parsing pkg list...
==> Making package: pyprland 1.3.1-1 (Sun 14 May 2023 12:49:39 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
HEAD is now at b117037 monitors: trigger the rules on init & reload
==> Starting build()...
/usr/bin/python: No module named build
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'pyprland-1.3.1-1':
error: packages failed to build: pyprland-1.3.1-1
```

Sorry for the text dump I'm still exploring wayland

**Comment by fdev31** [comment]
Thank you for the bug report, indeed, it looks like there was a wrong dependency, I just updated, can you confirm it's fixed ?

**Comment by biscuitrescue** [comment]
still failed to build

```
==> Making package: pyprland 1.3.1-2 (Wed 17 May 2023 01:29:22 PM IST)
==> Retrieving sources...
  -> Cloning pyprland git repo...
Cloning into bare repository '/home/cafo/.cache/paru/clone/pyprland/pyprland'...
remote: Enumerating objects: 292, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 292 (delta 27), reused 36 (delta 14), pack-reused 238
Receiving objects: 100% (292/292), 46.28 KiB | 1.13 MiB/s, done.
Resolving deltas: 100% (191/191), done.
==> Validating source files with md5sums...
    pyprland ... Skipped
==> Making package: pyprland 1.3.1-2 (Wed 17 May 2023 01:29:23 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating pyprland git repo...
==> Validating source files with md5sums...
    pyprland ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of pyprland git repo...
Cloning into 'pyprland'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
Note: switching to '1.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b117037 monitors: trigger the rules on init & reload
==> Sources are ready.
pyprland-1.3.1-2: parsing pkg list...
==> Making package: pyprland 1.3.1-2 (Wed 17 May 2023 01:29:26 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
HEAD is now at b117037 monitors: trigger the rules on init & reload
==> Starting build()...
* Getting build dependencies for wheel...
* Building wheel...
Successfully built pyprland-1.3.0-py3-none-any.whl
==> Entering fakeroot environment...
==> Starting package()...
/usr/bin/python: No module named installer
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'pyprland-1.3.1-2':
error: packages failed to build: pyprland-1.3.1-2
```

**Comment by Ultrahalf** [comment]
> Thank you for the bug report, indeed, it looks like there was a wrong dependency, I just updated, can you confirm it's fixed ?

nope


```
ERROR Backend 'poetry.core.masonry.api' is not available.
```

**Comment by fdev31** [comment]
I'm supposed to have it fixed in 1.3.1-3 ...
I'll test on a minimal installation to understand what's still missing. I may need to add poetry too indeed, but I didn't want to depend on it directly.

**Comment by Ultrahalf** [comment]
```
HEAD is now at b117037 monitors: trigger the rules on init & reload
==> Sources are ready.
pyprland-1.3.1-3: parsing pkg list...
==> Making package: pyprland 1.3.1-3 (Fri 19 May 2023 06:35:10 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
HEAD is now at b117037 monitors: trigger the rules on init & reload
==> Removing existing $pkgdir/ directory...
==> Starting build()...
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'

ERROR Backend 'poetry.core.masonry.api' is not available.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'pyprland-1.3.1-3':
error: packages failed to build: pyprland-1.3.1-3

```

**Comment by fdev31** [comment]
I added poetry too...  tell me if the latest version of the package still have some issues.

**Comment by Ultrahalf** [comment]
now it works. Thanks
I'll close this issue and fix the doc I think scratchpad doc is still using hpr... command instead of pypr in hyprland config in the readme
