### ISSUE TITLE
[BUG]  pyprland failed to start recently

### ISSUE THREAD

**Issue by TwelveNight** [hyprland-community/pyprland#67]
**Pyprland version**
archlinux aur pyprland

**Describe the bug**
```shell
❯ pypr        
Failed to load config.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 288, in run_daemon
    await manager.initialize()
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 56, in initialize
    await self.load_config()  # ensure sockets are connected first
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 135, in load_config
    await self.__open_config()
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 69, in __open_config
    self.config.update(tomllib.load(f))
                       ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tomllib/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tomllib/_parser.py", line 127, in loads
    raise suffixed_err(
tomllib.TOMLDecodeError: Expected newline or end of document after a statement (at 
```
![image](https://github.com/hyprland-community/pyprland/assets/113519679/08d22816-dd8e-4e29-86a9-88ce8f06e6bd)

**To Reproduce**
1. Go to 'terminal'
2. input pypr

**Expected behavior**
pyprland start

**Configuration (provide following files/samples when relevant):**
- pyprland.toml
```toml
[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
  "shift_monitors",
  "toggle_special",
]

[scratchpads.term]
lazy = true
command = "kitty ~/.config/hypr/scripts/tmux-scrachpad.sh"

# FIXME: this is not working
[scratchpads.warp]
lazy = true
command = "warp-terminal"

[scratchpads.volume]
animation = "fromtop" command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "70% 40%"
unfocus = "hide"

[scratchpads.thunar]
lazy = true
command = "thunar"

[scratchpads.nautilus]
lazy = true
command = "nautilus"


[scratchpads.firefox]
lazy = true
command = "firefox"


[scratchpads.firefox-nightly]
lazy = true
command = "firefox-nightly"

[scratchpads.thorium]
lazy = true
command = "thorium-browser"


[scratchpads.edge]
lazy = true
command = "microsoft-edge-stable"



```

**Comment by fdev31** [comment]
As mentioned in the error message, line 20 is incorrect:

animation = "fromtop" command = "pavucontrol"

should be

animation = "fromtop"
command = "pavucontrol"

**Comment by TwelveNight** [comment]
> As mentioned in the error message, line 20 is incorrect:
> 
> animation = "fromtop" command = "pavucontrol"
> 
> should be
> 
> animation = "fromtop" command = "pavucontrol"

sorry,my problem😅
